# Generated by Django 5.1.1 on 2024-11-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
