# Generated by Django 5.1.1 on 2024-11-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0002_cliente_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
