# Generated by Django 5.1.1 on 2024-12-01 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0003_remove_cliente_is_admin_alter_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='floreria.categoria'),
        ),
    ]
